<?xml version="1.0" encoding="UTF-8"?> 

<!DOCTYPE bibliografio [

<!ELEMENT bibliografio (vrk)*>
<!ELEMENT vrk (url?,aut*,trd?,tit?,ald?,eld*)>
<!ATTLIST vrk mll ID #REQUIRED> 
<!ELEMENT url (#PCDATA)>
<!ELEMENT aut (#PCDATA|a|n)*>
<!ELEMENT n   (#PCDATA)>
<!ELEMENT a   (#PCDATA)>
<!ELEMENT trd (#PCDATA|a|n)*>
<!ELEMENT tit (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT ald (#PCDATA)>
<!ELEMENT eld (nom?,lok?,dat?,nro?,isbn?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT lok (#PCDATA)>
<!ELEMENT dat (#PCDATA)>
<!ELEMENT nro (#PCDATA)>

<!ENTITY % signoj SYSTEM "../dtd/vokosgn.dtd">
%signoj;

<!ENTITY url_mjb "http://perso.club-internet.fr/kursoj/revo">

]>
 
<bibliografio>

  <vrk mll="BazRad">
    <url>http://www.xs4all.nl/~pilger/breo-al3.htm</url>
    <aut><a>Wouter F.</a> <n>Pilger</n></aut>
    <tit>Bazaj Radikoj Esperanto-Esperanto</tit>
  </vrk>

  <vrk mll="BEE">
    <aut><a>Montague J.</a> <n>Butler</n></aut>
    <tit>Esperanto-English Dictionary</tit>
    <eld>
       <nom>BEA</nom>
       <lok>London</lok>
       <dat>1967</dat>
    </eld>
  </vrk>

  <vrk mll="Bird">
    <aut><n>M&eacute;sz&aacute;ros</n> <a>B&eacute;la</a></aut>
    <tit>Oklingva nomaro de e&ubreve;ropaj birdoj</tit>
    <eld>
      <lok>Debrecen</lok>
      <dat>1980</dat>
    </eld>
  </vrk>

  <vrk mll="BoE">
    <aut><a>Werner</a> <n>Bormann</n></aut>
    <tit>Entrepreno. Entreprenistaj Strategioj: Priskribo de la
         entrepreno</tit>
    <eld>
      <nom>A&ubreve;toro</nom>
      <lok>Hamburg</lok>
      <dat>1991</dat>
    </eld>
  </vrk>

  <vrk mll="BoER">
    <url>http://www.esperanto.mv.ru/Vortaro/kovril.html</url>
    <aut><a>E.</a> <n>Bokarev</n></aut>
    <tit>Esperanta-rusa vortaro</tit>
    <eld>
      <lok>Moskvo</lok>
      <dat>1982</dat>
    </eld>
  </vrk>

  <vrk mll="BoM">
    <aut><a>Werner</a> <n>Bormann</n></aut>
    <tit>Mondkomerco kaj Lingvo</tit>
    <eld>
       <nom>A&ubreve;toro</nom>
       <lok>Hamburg</lok>
       <dat>1993</dat>
    </eld>
  </vrk>

  <vrk mll="BonaLingvo">
    <aut><a>Claude</a> <n>Piron</n></aut>
    <tit>La bona lingvo</tit>
    <eld>
      <nom>Pro Esperanto/HEA</nom>
      <lok>Vieno/Budape&scirc;to</lok>
      <dat>1989</dat>
    </eld>
  </vrk>

  <vrk mll="BonaS-ino">
    <aut><a>E.</a> <n>Orzeszko</n></aut>
    <trd><a>Karl</a> <n>Bein</n></trd>
    <tit>La bona sinjorino</tit>
  </vrk>

  <vrk mll="BoRE">
    <aut><a>E.</a> <n>Bokarev</n></aut>
    <tit>Rusa-esperanta vortaro</tit>
    <eld>
      <lok>Moskvo</lok>
      <dat>1966</dat>
    </eld>
  </vrk> 

  <vrk mll="BoT">
    <aut><a>Werner</a> <n>Bormann</n></aut>
    <tit>La Merkato de Trafikservoj</tit>
    <eld>
       <nom>A&ubreve;toro</nom>
       <lok>Hamburg</lok>
       <dat>1992</dat>
    </eld>
  </vrk>

  <vrk mll="BT">
    <aut>Douglas A. Portmann</aut>
    <tit>Biblioteka terminaro</tit>
  </vrk>

  <vrk mll="CCT">
    <tit>Common Commercial Terms in English and Esperanto</tit>
    <eld>
       <nom>The Esperanto Institute Limited</nom>
       <lok>Welwyn Garden City</lok>
       <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="CEE">
    <aut><a>Peter J.</a> <n>Benson</n></aut>
    <tit>Comprehensive English-Esperanto Dictionary</tit>
    <eld>
       <nom>ELNA</nom>
       <lok>El Cerrito</lok>
       <dat>1995</dat>
       <nro>1a eldono</nro>
       <isbn>0-939785-03-X</isbn>
    </eld>
  </vrk>

  <vrk mll="ChP">
    <aut><a>Petro</a> <n>Chrdle</n></aut>
    <tit>Profesia uzo de Esperanto kaj &gcirc;iaj specifaj trajtoj</tit>
    <eld>
       <nom>Kava-Pech</nom>
       <lok>Praha</lok>
       <dat>1995</dat>
       <nro>2a plilar&gcirc;igita eldono</nro>
    </eld>
  </vrk>

  <vrk mll="&Ccirc;A">
    <tit>&Ccirc;ina Antologio (1919-1949)</tit>
    <eld>
      <nom>&Ccirc;ina Esperanto-Eldonejo</nom>
      <lok>Pekino</lok>
      <dat>1986</dat>
    </eld>
  </vrk>

  <vrk mll="&ccirc;uSn">
    <aut><a>E.</a> <n>Lanti</n></aut>
    <tit>&Ccirc;u ili estas sennaciistoj?</tit>
  </vrk>

  <vrk mll="Dan&gcirc;Lng">
    <aut><a>Ulrich</a> <n>Lins</n></aut>
    <tit>La dan&gcirc;era lingvo</tit>
  </vrk>

  <vrk mll="DdH">
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <tit>Aldono al la &leftquot;Dogmoj de Hilelismo&rightquot;</tit>
    <eld>
      <nom>Ruslanda Esperantisto</nom>
      <dat>1906</dat>
    </eld>
  </vrk>

  <vrk mll="Deneva">
    <aut><a>Daniela</a> <n>Deneva</n></aut>
    <tit>Esperanta-Bulgara-Rusa Matematika Terminaro</tit>
    <eld>
      <nom>Bulgara Esperanto-Asocio</nom>
      <lok>Sofio</lok>
      <dat>1985</dat>
    </eld>
  </vrk>

  <vrk mll="DOz">
    <url>http://ttt.esperanto.org/esperante/literatur/Baum/doroteo/</url>
    <aut><a>L. Frank</a> <n>Baum</n></aut>
    <trd><a>D.</a> <n>Broadribb</n></trd>
    <tit>Doroteo kaj la Sorcxisto en Oz</tit>
    <eld>
      <nom>Bookleaf Publishing</nom>
      <lok>A&ubreve;stralio</lok>
      <dat>1996</dat>
    </eld>
  </vrk>

  <vrk mll="EBV">
    <aut><a>R&uuml;diger</a> <n>Eichholz</n></aut>
    <tit>Esperanta Bildvortaro</tit>
    <eld>
      <nom>Esperanto press</nom>
      <lok>Bailieboro, Ontario, Kanado</lok>
      <dat>1989</dat>
      <nro>2a eldono</nro>
      <isbn>0-919186-32-7</isbn>
    </eld>
  </vrk>

  <vrk mll="EdE">
    <tit>Enciklopedio de Esperanto</tit>
    <eld>
      <lok>Budapest</lok>
      <dat>1979</dat>
      <isbn>963-571-051-8</isbn>
    </eld>
  </vrk>

  <vrk mll="EE">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url>
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <tit>Esenco kaj Estonteco</tit>
  </vrk>

  <vrk mll="Eek">
    <tit>Esperanto en Komerco. Esperanto in Commerce</tit>
    <eld>
       <nom>Esperanto-Rondo</nom>
       <lok>Crailsheim</lok>
       <dat>1964</dat>
       <nro>3a eldono</nro>
    </eld>
  </vrk>

  <vrk mll="EFM">
    <aut><n>Braun</n></aut>
    <aut><n>Polerani</n></aut>
    <aut><n>Rotsaert</n></aut>
    <aut><n>Wiersch</n></aut>
    <aut><n>Yamasaki</n></aut>
    <aut><n>Ruysschaert</n></aut>
    <tit>Economie, finance, monnaie. Glosaro de la komisiono de la
         E&ubreve;ropaj
         Komunumoj. Versio esperanto &dash; fran&ccedil;ais &dash; english
    </tit>
    <eld>
       <nom>IKEF</nom>
       <lok>Welzheim</lok>
       <dat>1992</dat>
    </eld>
  </vrk>

  <vrk mll="Ekolud">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/ludoj/ekoludo.html</url>
    <tit>Ekoludo</tit>
  </vrk>

  <vrk mll="EKV">
    <aut><a>R.</a> <n>Hilgers</n></aut>
    <aut><n>Yashovardhan</n></aut>
    <aut>k.a.</aut>
    <tit>EK-Vortaro de matematikaj terminoj</tit>
    <ald>vol. 4 en E&ubreve;ropa Serio: Sennaciigita Scienco</ald>
    <eld>
      <nom>E&ubreve;ropa Klubo, FEoLL-Institut f&uuml;r 
           Kybernetische P&auml;dagogik</nom>
      <lok>Paderborn</lok>
      <dat>1980</dat>
      <isbn>3-88064-080-7</isbn>
    </eld>
  </vrk>

  <vrk mll="EncCxi">
    <aut><a>Li</a> <n>Qiang</n></aut>
    <aut><a>Zhang</a> <n>Meizhi</n></aut>
    <trd>Fan Yizhu, Xu Senrong</trd>
    <tit>Enciklopedieto de &Ccirc;inio</tit>
    <eld>
      <nom>&Ccirc;ina Esperanto-Eldonejo</nom>
      <lok>Beijing</lok>
      <dat>1994</dat>
      <isbn>7-5052-0086-0/Z.4</isbn>
    </eld>
  </vrk>

  <vrk mll="EncJap">
    <aut><a>T.</a> <n>Nakamura</n></aut>
    <tit>Enciklopedieto japana</tit>
    <eld>
      <nom>eldono de kosmo</nom>
      <lok>Osaka</lok>
      <dat>1964</dat>
    </eld>
  </vrk>

  <vrk mll="F">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url>
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <tit>Fundamento de Esperanto</tit>
    <eld>
      <lok>Varsovio</lok>
      <dat>1905</dat>
    </eld>
  </vrk>

  <vrk mll="Fab1">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/fabeloj1/</url>
    <aut><a>H. C.</a> <n>Andersen</n></aut>
    <trd><a>L. L.</a> <n>Zamenhof</n></trd>
    <tit>Fabeloj, vol. 1</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="Fab2">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/fabeloj2/</url>
    <aut><a>H. C.</a> <n>Andersen</n></aut>
    <trd><a>L. L.</a> <n>Zamenhof</n></trd>
    <tit>Fabeloj, vol. 2</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="Fab3">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/fabeloj3/</url>
    <aut><a>H. C.</a> <n>Andersen</n></aut>
    <trd><a>L. L.</a> <n>Zamenhof</n></trd>
    <tit>Fabeloj, vol. 3</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1932</dat>
    </eld>
  </vrk>

  <vrk mll="Fab4">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/fabeloj4/</url>
    <aut><a>H. C.</a> <n>Andersen</n></aut>
    <trd><a>L. L.</a> <n>Zamenhof</n></trd>
    <tit>Fabeloj, vol. 4</tit>
    <eld>
      <nom>Heroldo de Esperanto</nom>
      <dat>1963</dat>
    </eld>
  </vrk>
  
  <vrk mll="Far1">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/faraono1/</url>
    <aut><a>B.</a> <n>Prus</n></aut>
    <trd><a>K.</a> <n>Bein</n></trd>
    <tit>La Faraono, vol. 1</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1927</dat>
    </eld>
  </vrk>

  <vrk mll="Far2">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/faraono2/</url>
    <aut><a>B.</a> <n>Prus</n></aut>
    <trd><a>K.</a> <n>Bein</n></trd>
    <tit>La Faraono, vol. 2</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="Far3">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/faraono3/</url>
    <aut><a>B.</a> <n>Prus</n></aut>
    <trd><a>K.</a> <n>Bein</n></trd>
    <tit>La Faraono, vol. 3</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="FIL">
    <tit>
      Pri la solvo de l'problemo de internacia lingvo por komerco kaj
      trafiko. Zur L&ouml;sung der Frage einer internationalen Handels- und
      Verkehrssprache. Amtlicher Sitzungsbericht der 
      Internationalen Konferenz f&uuml;r eine gemeinsame 
      Hilfssprache des Handels und Verkehrs, Venedig, 2.-4. April
      1923
    </tit>
    <eld>
       <nom>Frankfurter Messamt</nom>
       <lok>Frankfurt a.M.</lok>
       <dat>1923</dat>
    </eld>
  </vrk>

  <vrk mll="FT">
    <tit>Fervoja Terminaro</tit>
    <ald>UIC Railway Dictionary</ald>
    <eld>
      <nom>EFE - Terminara Komisiono</nom>
      <dat>1997</dat>
    </eld>
  </vrk>

  <vrk mll="FzT">
    <aut><n>Katsumori</n> <a>H.</a></aut>
    <aut><n>Makino</n> <a>S.</a></aut>
    <aut><n>Makino</n> <a>J.</a> (komp.)</aut>
    <tit>Esperanta terminaro de fiziko, Esperanto &dash; japana &dash; angla.
         Reviziita
    </tit>
    <eld>
       <nom>Universitato Chubu</nom>
       <lok>Chubu, Japanio</lok>
       <dat>1992</dat>
       <isbn>0-939785-03-X</isbn>
    </eld>
  </vrk>

  <vrk mll="GDFE">
    <aut><a>Jacques</a> <n>Le Puil</n></aut>
    <aut><a>Jean-Pierre</a> <n>Danvy</n></aut>
    <aut>k.a.</aut>
    <tit>Grand dictionnaire fran&ccedil;ais esp&eacute;ranto</tit>
    <eld>
      <nom>France-Esp&eacute;ranto</nom>
      <lok>Parizo</lok>
      <dat>1992</dat>
      <isbn>2-9507376-0-9</isbn>
    </eld>
  </vrk>

  <vrk mll="Gerda">
    <url>&url_mjb;/gerda1.txt</url>
    <aut><a>Claude</a> <n>Piron</n></aut>
    <tit>Gerda malaperis</tit>
    <eld>
      <nom>Fonto</nom>
    </eld>
  </vrk>

  <vrk mll="Gv">
    <aut><a>Claus</a> <n>G&uuml;nkel</n> (Nikolao)</aut>
    <tit>La Gunkela vortaro de vortoj mankantaj en PIV 2002</tit>
    <eld>
       <nom>Propra eldono</nom>
       <lok>Eschweiler</lok>
       <dat>2002</dat>
    </eld>
  </vrk>

  <vrk mll="HejmVort">
    <url>http://www.helsinki.fi/~jslindst/hejmvort.html</url>
    <aut><a>Jouko</a> <n>Lindstedt</n></aut>
    <aut>k.a.</aut>
    <tit>Hejma Vortaro</tit>
    <eld>
      <nom>Universala Esperanto-Asocio</nom>
      <lok>Rotterdam</lok>
      <dat>1999</dat>
    </eld>
  </vrk>

  <vrk mll="Homaranismo">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url> 
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <tit>Homaranismo</tit>
    <eld>
      <nom>Ruslanda Esperantisto</nom>
      <lok>Peterburgo</lok>
      <dat>1906</dat>
      <nro>n-ro 5</nro>
    </eld>
  </vrk>  

  <vrk mll="IKEV">
    <aut><a>F.</a> <n>Munniksma</n> (eld.)</aut>
    <tit>Internacia komerca-ekonomika vortaro en 11 lingvoj</tit>
    <eld>
       <nom>&Ccirc;ina Esperanto-eldonejo</nom>
       <lok>Pekino</lok>
       <dat>1990</dat>
       <isbn>7-5052-0025-9</isbn>
    </eld>
  </vrk>

  <vrk mll="IntKui">
    <aut><a>Maria</a> <n>Becker-Meisberger</n></aut>
    <tit>Internacie kuiri</tit>
    <eld>
      <nom>Flandra Esperanto-Ligo</nom>
      <lok>Antwerpen</lok>
      <dat>2000</dat>
      <isbn>90-71205-70-3</isbn>
    </eld>
  </vrk>

  <vrk mll="I&scirc;tar">
    <url>http://home.att.net/~karlpov/proisxtr.htm</url>
    <aut><a>H. A.</a> <n>Luyken</n></aut>
    <tit>Pro I&scirc;tar</tit>
    <eld>
      <nom>Ferdinand Hirt &amp; Sohn</nom>
      <lok>Lepsiko</lok>
      <dat>1924</dat>
    </eld>
  </vrk>

  <vrk mll="ItEsp">
    <aut><a>Carlo</a> <n>Minnaja</n></aut>
    <tit>Vocabolario Italiano-Esperanto</tit>
    <eld>
      <nom>CoEdEs</nom>
      <dat>1996</dat>
    </eld>
  </vrk>

  <vrk mll="JuanReg">
    <aut><n>Albault</n></aut>
    <aut><n>Ariste</n></aut>
    <aut><n>Auld</n></aut>
    <aut>k.a.</aut>
    <tit>Serta gratulatoria in honorem Juan R&eacute;gulo</tit>
    <eld>
      <nom>Universitato de La Laguna</nom>
      <lok>Kanariaj Insuloj</lok>
      <dat>1987</dat>  
    </eld>
  </vrk> 

  <vrk mll="JV">
    <aut><n>Horba&ccirc;uk</n>, <a>V.</a></aut>
    <aut><n>Poddubnij</n>, <a>F.</a></aut>
    <aut><n>Tu&hcirc;vatullina</n>, <a>L.</a></aut>
    <aut><n>&Scirc;ilo</n>, <a>G.</a></aut>
    <tit>Jura Vortaro esperante-ruse-ukraine-angla</tit>
    <eld>
       <nom>Akademia Centro de Administro, Entreprenado, Juro</nom>
       <lok>Slavjansk</lok>
       <dat>1994</dat>
    </eld>
  </vrk>

  <vrk mll="KelS">
    <tit>Kajeroj el la Sudo</tit>
  </vrk>

  <vrk mll="KompLeks">
    <url>http://purl.oclc.org/NET/voko/URL/KompLeks/</url>
    <aut><a>Sergio</a> <n>Pokrovskij</n></aut>
    <tit>Komputila Leksikono</tit>
  </vrk>

  <vrk mll="Kosmo">
    <aut><a>David</a> <n>Galad&iacute;-Enr&iacute;quez</n></aut>
    <aut><a>Amri</a> <n>Wandel</n></aut>
    <tit>La kosmo kaj ni &dash; Galaksioj, planedoj kaj vivo en la universo</tit> 
    <eld>
      <nom>Flandra Esperanto-Ligo</nom>
      <lok>Antverpeno</lok>
      <dat>2001</dat>
    </eld>
  </vrk>

  <vrk mll="KrED">
    <aut><a>Erich Dieter</a> <n>Krause</n></aut>
    <tit>Gro&szlig;es W&ouml;rterbuch Esperanto-Deutsch</tit>
    <eld>
      <nom>Langenscheidt</nom>
      <lok>Hamburg</lok>
      <dat>1999</dat>
    </eld>
  </vrk>

  <vrk mll="KrDE">
    <aut><a>Erich Dieter</a> <n>Krause</n></aut>
    <tit>W&ouml;rterbuch Deutsch-Esperanto</tit>
    <eld>
      <nom>Langenscheidt</nom>
      <lok>Leipzig k.a.</lok>
      <dat>1993</dat>
    </eld>
  </vrk>

  <vrk mll="Kukobak">
    <url>http://www.uni-leipzig.de/esperanto/texte/bakado.html</url>
    <aut><a>Cornelia</a> <n>Rau</n></aut>
    <aut>k.a.</aut>
    <tit>Kukobakado</tit>
    <eld>
      <nom>Wolfram Diestel</nom>
      <lok>Lepsiko</lok>
      <dat>1993</dat>
    </eld>
  </vrk>

  <vrk mll="KVS">
    <aut><a>Robert</a> <n>Kreuz</n></aut>
    <tit>Komerca Vortaro Seslingva. Germana &dash; Angla &dash; Franca &dash; Itala &dash;
         Hispana &dash; Esperanta
    </tit>
    <eld>
      <nom>Foira Oficejo</nom>
      <lok>Frankfurt a.M.</lok>
      <dat>1927</dat>
    </eld>
  </vrk>

  <vrk mll="Lanti">
    <aut><a>E.</a> <n>Lanti</n></aut>
    <tit>Vortoj de k-do Lanti</tit>
    <eld>
      <nom>Sennacieca Asocio Tutmonda</nom>
      <dat>1931</dat>
    </eld>
  </vrk>

  <vrk mll="Lasu">
    <url>&url_mjb;/lasu1.txt</url>
    <aut><a>Claude</a> <n>Piron</n></aut>
    <tit>Lasu min paroli plu!</tit>
    <eld>
      <nom>Fonto</nom>
    </eld>
  </vrk>

  <vrk mll="Lkn">
    <aut><a>Ricardo</a> <n>&Scirc;ulco</n></aut>
    <aut><a>Hermano</a> <n>Bermano</n></aut>
    <tit>Leksara kolekto de ofte uzataj propraj nomoj</tit>
    <eld>
       <nom>ECP</nom>
       <lok>Paderborno</lok>
       <dat>1989</dat>
       <nro>1a eldono</nro>
       <isbn>3-922570-60-7</isbn>
    </eld>
  </vrk>

  <vrk mll="LOdE">
    <url>http://www.esperanto.org/Ondo/</url>
    <tit>La Ondo de Esperanto</tit>
    <ald>Gazeto</ald>
    <eld>
      <nom>Sezonoj</nom>
      <lok>Ruslando</lok>
    </eld>
  </vrk>

  <vrk mll="LR">
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <tit>Lingvaj Respondoj</tit>
  </vrk>

  <vrk mll="LSF">
    <aut><n>Kalocsay</n></aut>
    <tit>Lingvo, Stilo, Formo</tit>
    <eld>
      <lok>Budapest</lok>
      <dat>1931</dat>
    </eld>
  </vrk>

  <vrk mll="LSV">
    <aut><a>E.</a> <n>Lanti</n></aut>
    <tit>&leftquot;Liberiga Stelo&rightquot; al la
    Verdru&gcirc;uloj</tit>
  </vrk>

  <vrk mll="LtE">
    <aut><a>Henrik</a> <n>Seppik</n></aut>
    <tit>La tuta Esperanto</tit>
    <eld>
      <nom>Hungara Esperanto-Asocio</nom>
      <lok>Budapest</lok>
      <dat>1987</dat>
      <nro>4a eldono</nro>
      <isbn>963-571-196-4</isbn>
    </eld>
  </vrk>

  <vrk mll="Mary">
    <aut><a>M.</a> <n>Lermontov</n></aut>
    <trd><a>N.</a> <n>Danovskij</n></trd>
    <tit>Princidino Mary</tit>
    <eld>
      <nom>Ruslanda Esperantisto</nom>
      <lok>Jekaterinburg</lok>
      <dat>1996</dat>
    </eld>
  </vrk>

  <vrk mll="Malben">
    <url>http://www.books-reborn.org/broadribb/malbeno/MalbenoKara.pdf</url>
    <aut><a>Mary</a> <n>Webb</n></aut>
    <trd><a>Grace</a> <n>Kirkwood</n></trd>
    <tit>Malbeno Kara</tit>
    <eld>
      <nom>Books Reborn</nom>
      <dat>2000</dat>
    </eld>
  </vrk>

  <vrk mll="ManPol">
    <aut><a>Stefan</a> <n>Maul</n></aut>
    <aut>k. a.</aut>
    <tit>Deklingva manlibro pri politiko</tit>
    <eld>
      <nom>Flandra Esperanto-Ligo</nom> 
      <lok>Antverpeno</lok>
      <dat>1994</dat>
    </eld>
  </vrk>

  <vrk mll="Marta">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/marta/</url>
    <aut><a>Eliza</a> <n>Orzeszkowa</n></aut>
    <trd><a>L. L.</a> <n>Zamenhof</n></trd>
    <tit>Marta</tit>
    <eld>
      <nom>Esperantista Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1924</dat>
      <nro>2a eldono</nro>
    </eld>
  </vrk>

  <vrk mll="MatStokTerm">
    <aut><a>Olav</a> <n>Reiers&#xf8;l</n></aut>
    <tit>Matematika kaj Stokastika Terminaro Esperanta</tit>
    <eld>
      <lok>Oslo</lok>
      <dat>1994</dat>
      <nro>dua eldono</nro>
      <isbn>82-553-0894-6</isbn>
    </eld>
  </vrk>

  <vrk mll="MatTerm">
    <url>&url_mjb;/MatTerm.tif</url>
    <aut><a>Raoul</a> <n>Bricard</n></aut>
    <tit>Matematika Terminaro kaj Krestomatio</tit>
    <eld>
      <nom>Hachette</nom>
      <lok>Parizo</lok>
      <dat>1905</dat>
    </eld>
  </vrk>

  <vrk mll="MatVort">
    <url>&url_mjb;/werner.htm</url>
    <aut><a>Jan</a> <n>Werner</n></aut>
    <tit>Matematika Vortaro, Esperanta-&Ccirc;e&hcirc;a-Germana</tit>
    <eld>
      <lok>Brno</lok>
      <dat>1990</dat>
    </eld>
  </vrk>

  <vrk mll="MB">
    <tit>Malbabelo</tit>
    <ald>Gazeto de la Frankfurtmajna Esperanto-Societo</ald>
    <eld>
      <nom>ESF</nom>
      <lok>Frankfurto &ccirc;e Majno</lok>
      <dat>1994-</dat>
    </eld>
  </vrk>

  <vrk mll="MemLapenna">
    <url>http://www.geocities.com/CapitolHill/Senate/1240/memore.html</url>
    <aut><a>Birthe</a> <n>Lapenna</n></aut>
    <tit>Memore al Ivo Lapenna</tit>
    <ald>La kreinto de la moderna Esperanto-Movado</ald>
    <eld>
      <nom>Fonda&jcirc;o Ivo Lapenna</nom>
      <lok>Interreto</lok>
      <dat>1998</dat>
    </eld>
  </vrk>

  <vrk mll="Metrop">
    <aut><a>V.</a> <n>Varankin</n></aut>
    <tit>Metropoliteno</tit>
  </vrk>

  <vrk mll="MEV">
    <aut><a>Eugen</a> <n>W&uuml;ster</n></aut>
    <tit>Ma&scirc;infaka Esperanto-vortaro</tit>
    <eld>
       <nom>Ferdinand Hirt und Sohn</nom>
       <lok>Leipzig</lok>
       <dat>1923</dat>
    </eld>
  </vrk>

  <vrk mll="MkM">
    <url>http://www.esperanto.mv.ru/MM/</url>
    <aut><a>Mihail</a> <n>Bulgakov</n></aut>
    <trd><a>Sergio</a> <n>Pokrovskij</n></trd>
    <tit>La majstro kaj Margarita</tit>
    <eld>
      <nom>Sezonoj</nom>
      <lok>Jekaterinburg</lok>
      <dat>1991</dat>
    </eld>
  </vrk>

  <vrk mll="Monato">
    <url>http://www.esperanto.be/monato/</url>
    <tit>Monato</tit>
    <ald>internacia magazino</ald>
    <eld>
      <nom>Flandra Esperanto-Ligo</nom>
      <lok>Belgio</lok>
    </eld>
  </vrk>

  <vrk mll="MT">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/biblio/</url>
    <trd><a>L. L.</a> <n>Zamenhof</n></trd>
    <tit>La Malnova Testamento</tit>
    <eld>
      <nom>Brita kaj Alilanda Biblia Societo</nom>
      <lok>Londono</lok>
    </eld>
  </vrk>

  <vrk mll="MuzTerm">
    <aut><a>M. C.</a> <n>Butler</n></aut>
    <aut><a>F.</a> <n>Merrick</n></aut>
    <aut><a>D. G.</a> <n>Hill</n> ind.</aut>
    <tit>Muzika terminaro</tit>
    <ald>represo de la eldono fare de Internacia Esperanto-Ligo, 1944</ald>
    <eld>
      <nom>Muzika Esperanto-Ligo</nom>
      <lok>Sofio</lok>
      <dat>1992</dat>
    </eld>
  </vrk>

  <vrk mll="NeoGlo">
    <aut><a>H.</a> <n>Vatr&eacute;</n></aut>
    <tit>Neologisma glosaro, postrikolto al PIV</tit>
    <ald>tria eldono kun la&ubreve;tema klasifiko kaj rimaro en
        suplemento</ald>
    <eld>
      <nom>Artur E. Iltis</nom>
      <lok>Saarbr&uuml;cken</lok>
      <dat>1989</dat>
      <isbn>3-927613-07-X</isbn>
    </eld>
  </vrk>

  <vrk mll="NePiv">
    <aut><a>A.</a> <n>Cherpillod</n></aut>
    <tit>Nepivaj vortoj</tit>
    <ald>listo de 6800 vortoj ne trovi&gcirc;antaj en la PIV el kiuj kelkaj
         povas esti utilaj</ald>
    <eld>
      <nom>la a&ubreve;toro</nom>
      <lok>Courgenard Francio</lok>
      <dat>1988</dat>
      <isbn>2-906134-05-8</isbn>
    </eld>
  </vrk>
 
  <vrk mll="NT">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/biblio</url>
    <tit>La Nova Testamento</tit>
    <ald>de nia Sinjoro kaj Savanto Jesuo Kristo</ald>
    <eld>
      <nom>Brita kaj Alilanda Biblia Societo</nom>
      <lok>Londono</lok>
    </eld>
  </vrk>

  <vrk mll="OV">
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <tit>Originala Verkaro</tit>
  </vrk>

  <vrk mll="PatrojFiloj">
    <aut><a>I. S.</a> <n>Turgenjev</n></aut>
    <trd><a>Kazimierz</a> <n>Bein</n></trd>
    <tit>Patroj kaj filoj</tit> 
    <eld>
      <nom>Libroservo Federacio de laboristaj esperantistoj</nom>
      <lok>Amsterdamo</lok>
      <dat>[proks. 1938]</dat>
    </eld>
  </vrk>

  <vrk mll="PGl">
    <aut><n>Kalocyay</n></aut>
    <aut><n>Waringhien</n></aut>
    <aut><n>Bernard</n></aut>
    <tit>Parnasa Gvidlibro</tit>
    <eld>
      <lok>Pisa</lok>
      <dat>1984</dat>
    </eld>
  </vrk>

  <vrk mll="Paroloj">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/paroloj/</url>
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <tit>Paroloj</tit>
  </vrk>

  <vrk mll="PIV1">
    <tit>Plena Ilustrita Vortaro</tit>
    <eld>
      <nom>SAT</nom>
      <lok>Parizo</lok>
      <dat>1970</dat>
    </eld>
  </vrk>

  <vrk mll="PIV2">
    <tit>La Nova Plena Ilustrita Vortaro</tit>
    <eld>
      <nom>SAT</nom>
      <lok>Parizo</lok>
      <dat>2002</dat>
    </eld>
  </vrk>

  <vrk mll="PMEG">
    <url>http://purl.oclc.org/net/pmeg/</url>
    <aut><a>Bertilo</a> <n>Wennergren</n></aut>
    <tit>Plena Manlibro de Esperanta Gramatiko</tit>
  </vrk>

  <vrk mll="PV">
    <aut><a>E.</a> <n>Grosjean-Maupin</n></aut>
    <tit>Plena Vortaro de Esperanto</tit>
    <eld>
      <nom>SAT</nom>
      <lok>Parizo</lok>
      <dat>1934</dat>
    </eld>
  </vrk>

  <vrk mll="PrV">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url>
    <aut><a>L. L.</a> <n>Zamenhof</n></aut>
    <aut><a>C.</a> <n>Rogister</n> ed.</aut>
    <tit>Proverbaro esperanta</tit>
    <eld>
      <nom>Stafeto</nom>
      <lok>La Laguna</lok>
      <dat>1974</dat>
      <isbn>400-7609-6</isbn>
    </eld>
  </vrk>

  <vrk mll="RabistFab">
    <url>http://mujweb.atlas.cz/Kultura/malovec/RABISTA1.HTM</url>
    <aut><a>Josef</a> <n>&Ccaron;apek</n></aut>
    <tit>La unua rabista fabelo</tit>
  </vrk>

  <vrk mll="Revadoj">
    <aut><a>Jean-Jacques</a> <n>Rousseau</n></aut>
    <trd><a>Andr&eacute;</a> <n>Gilles</n></trd>
    <tit>La revadoj de soleca promenanto</tit>
    <ald>Franca Esperantisto, kaj. 414 (09/1990) kaj 420 (04/1991)</ald>
    <eld>
      <nom>Unui&gcirc;o Franca por Esperanto, 
        &ccirc;e Flandra Esperanto-Ligo</nom>
    </eld>
  </vrk>

  <vrk mll="Revizoro">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/revizoro/index.html</url>
    <aut><a>N. V.</a> <n>Gogol</n></aut>
    <trd><a>L. L.</a> <n>Zamenhof</n></trd>
    <tit>La Revizoro</tit>
  </vrk>

  <vrk mll="RokPop">
    <url>http://purl.oclc.org/net/bertilow?d=roko/index.php</url>
    <aut><a>B.</a> <n>Wennergren</n></aut>
    <tit>Roko kaj Popo, Popularmuzika Terminaro en Esperanto</tit>
  </vrk>

  <vrk mll="RugxDom">
    <aut><a>Cao</a> <n>Xueqin</n></aut>
    <trd><a>Xie</a> <n>Yuming</n></trd>
    <tit>Ru&gcirc;doma son&gcirc;o</tit>
    <eld>
      <nom>&Ccirc;ina Esperanto-Eldonejo</nom>
      <lok>Beijing</lok>
      <dat>1995</dat>
      <isbn>7-5052-0235-9</isbn>
    </eld>
  </vrk>

  <vrk mll="Salamandroj">
    <aut><a>Karel</a> <n>&Ccaron;apek</n></aut>
    <trd><a>J.</a> <n>Vondrou&scaron;ek</n></trd>
    <tit>Milito kontra&ubreve; salamandroj</tit>
  </vrk>

  <vrk mll="SPIV">
    <tit>Plena Ilustrita Vortaro de Esperanto, Suplemento</tit>
    <eld>
      <nom>SAT</nom>
      <lok>Parizo</lok>
      <dat>1987</dat>
    </eld>
  </vrk>

  <vrk mll="TermKurs">
    <aut><a>Jan</a> <n>Werner</n></aut>
    <tit>Terminologia Kurso</tit>
    <eld>
      <nom>Sdru&zcaron;en&yacute; klub ROH</nom>
      <lok>Roudnice nad Labem</lok>
      <dat>1986</dat>
    </eld>
  </vrk>

  <vrk mll="TK">
    <aut></aut>
    <tit>Ilustrita terminaro de kombinita transporto, franca, angla, germana,
     esperanta, serba</tit>
    <eld>
       <nom>Interpres 1847</nom>
       <lok>Beogrado</lok>
       <dat>1998</dat>
    </eld>
  </vrk>

  <vrk mll="TW">
    <aut><a>Rudolf</a> <n>Haferkorn</n></aut>
    <tit>Technisches W&ouml;rterbuch Deutsch-Esperanto</tit>
    <eld>
       <nom>Esperanto Press</nom>
       <lok>Cardiff</lok>
       <dat>1967</dat>
    </eld>
  </vrk>

  <vrk mll="UrdHadda">
    <aut><a>Deck</a> <n>Dorval</n></aut>
    <tit>Urd Hadda murdita!</tit>
    <ald>Serio Stafeto, n-ro 13</ald>
    <eld>
      <nom>Flandra Esperanto-Ligo</nom>
      <lok>Antwerpen</lok>
      <dat>1990</dat>
      <isbn>90-71205-37-1</isbn>
    </eld>
  </vrk>

  <vrk mll="VdE">
    <aut><a>Karl</a> <n>Bein</n></aut>
    <tit>Vortaro de Esperanto</tit>
    <eld>
      <nom>Hachette</nom>
      <lok>Parizo</lok>
      <dat>1912</dat>
    </eld>
  </vrk>

  <vrk mll="Viki">
     <url>http://eo.wikipedia.com/</url>
     <tit>Vikipedio</tit>
  </vrk>

  <vrk mll="VivZam">
    <aut><a>Edmond</a> <n>Privat</n></aut>
    <tit>Vivo de Zamenhof</tit> 
    <eld>
      <nom>The Esperanto publishing co. ltd</nom>
      <lok>Heronsgate</lok>
      <dat>1937</dat>
      <nro>2a eldono</nro>
    </eld>
  </vrk>

  <vrk mll="WAPS">
    <aut><a>William</a> <n>Auld</n></aut>
    <tit>Pajleroj kaj stoploj</tit>
    <eld>
      <nom>Universala Esperanto-Asocio</nom>
      <lok>Rotterdam</lok>
      <dat>1997</dat>
      <isbn>92-9017-052-2</isbn>
    </eld>
  </vrk>

  <vrk mll="WED">
    <aut><a>J.C.</a> <n>Wells</n></aut>
    <tit>Esperanto Dictionary Esperanto-English, English-Esperanto</tit>
    <eld>
       <nom>Teach Yourself Books</nom>
       <lok>London</lok>
       <dat>1969</dat>
    </eld>
  </vrk>

  <vrk mll="ZR">
    <aut><a>Eugen</a> <n>W&uuml;ster</n></aut>
    <tit>Zamenhof-radikaro</tit>
    <eld>
      <nom>Ferdinand Hirt und Sohn</nom>
      <lok>Leipzig</lok>
      <dat>1927</dat>
    </eld>
  </vrk>

</bibliografio>








