<?xml version="1.0" encoding="UTF-8"?> 

<!DOCTYPE bibliografio [

<!ELEMENT vrk (url?,aut?,trd?,tit?,ald?,eld?)>
<!ATTLIST vrk mll ID #REQUIRED> 
<!ELEMENT url (#PCDATA)>
<!ELEMENT aut (#PCDATA)>
<!ELEMENT trd (#PCDATA)>
<!ELEMENT tit (#PCDATA)>
<!ELEMENT ald (#PCDATA)>
<!ELEMENT eld (nom?,lok?,jar?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT lok (#PCDATA)>
<!ELEMENT dat (#PCDATA)>

]>
 
<bibliografio>

  <vrk mll="F">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url>
    <aut>L. L. Zamenhof</aut>
    <tit>Fundamento de Esperanto</tit>
    <eld>
      <lok>Varsovio</lok>
      <dat>1905</dat>
    </eld>
  </vrk>

  <vrk mll="M">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url>
    <trd>L. L. Zamenhof</trd>
    <tit>Malnova Testamento</tit>
  </vrk>

  <vrk mll="X">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/html</url>
    <trd>L. L. Zamenhof</trd>
    <tit>Nova Testamento</tit>
  </vrk>

  <vrk mll="PIV1">
    <tit>Plena Ilustrita Vortaro</tit>
    <eld>
      <nom>SAT</nom>
      <lok>Parizo</lok>
      <dat>1970</dat>
    </eld>
  </vrk>

  <vrk mll="KompLeks">
    <url>http://purl.oclc.org/NET/voko/URL/KompLeks/</url>
    <aut>Sergio Pokrovskij</aut>
    <tit>Komputila Leksikono</tit>
  </vrk>
  
  <vrk mll="Bird">
    <aut>Mészáros Béla</aut>
    <tit>Oklingva nomaro de eŭropaj birdoj</tit>
    <eld>
      <lok>Debrecen</lok>
      <dat>1980</dat>
    </eld>
  </vrk>

  <vrk mll="PV">
    <aut>E. Grosjean-Maupin</aut>
    <tit>Plena Vortaro de Esperanto</tit>
    <eld>
      <nom>SAT</nom>
      <lok>Parizo</lok>
      <dat>1934</dat>
    </eld>
  </vrk>

  <vrk mll="EE">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url>
    <aut>L. L. Zamenhof</aut>
    <tit>Esenco kaj Estonteco</tit>
  </vrk>
  
  <vrk mll="Far1">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/faraono/vol1/</url>
    <aut>B. Prus</aut>
    <trd>K. Bein</trd>
    <tit>La Faraono, vol. 1</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1927</dat>
    </eld>
  </vrk>

  <vrk mll="Far2">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/faraono/vol2/</url>
    <aut>B. Prus</aut>
    <trd>K. Bein</trd>
    <tit>La Faraono, vol. 2</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="Far3">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/faraono/vol3/</url>
    <aut>B. Prus</aut>
    <trd>K. Bein</trd>
    <tit>La Faraono, vol. 3</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1927</dat>
    </eld>
  </vrk>

  <vrk mll="PrV">
    <url>ftp://ftp.esperanto.org/publika/tekstoj/</url>
    <aut>L. L. Zamenhof</aut>
    <tit>Proverbaro</tit>
  </vrk>

  <vrk mll="Fab1">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/fabeloj_andersen/</url>
    <aut>H. C. Andersen</aut>
    <trd>L. L. Zamenhof</trd>
    <tit>Fabeloj, vol. 1</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="Fab2">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/fabeloj_andersen/</url>
    <aut>H. C. Andersen</aut>
    <trd>L. L. Zamenhof</trd>
    <tit>Fabeloj, vol. 2</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1926</dat>
    </eld>
  </vrk>

  <vrk mll="Fab3">
    <url>http://www.uni-leipzig.de/esperanto/texte/bibl/fabeloj_andersen/tria_vol/</url>
    <aut>H. C. Andersen</aut>
    <trd>L. L. Zamenhof</trd>
    <tit>Fabeloj, vol. 3</tit>
    <eld>
      <nom>Esp. Centra Librejo</nom>
      <lok>Parizo</lok>
      <dat>1932</dat>
    </eld>
  </vrk>

  <vrk mll="HejmVort">
    <url>http://www.helsinki.fi/~jslindst/hejmvort.html</url>
    <aut>Jouko Lindstedt k.a.</aut>
    <tit>Hejma Vortaro</tit>
    <eld>
      <nom>Universala Esperanto-Asocio</nom>
      <lok>Rotterdam</lok>
      <dat>1999</dat>
    </eld>
  </vrk>

  <vrk mll="Monato">
    <url>http://www.esperanto.be/monato/</url>
    <tit>Monato</tit>
    <ald>internacia magazino</ald>
    <eld>
      <nom>Flandra Esperanto-Ligo</nom>
      <lok>Belgio</lok>
    </eld>
  </vrk>

</bibliografio>







